services:
  - type: web
    name: yadav-krishna-portfolio
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    headers:
      - path: "/*"
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: "/*"
        name: X-Content-Type-Options
        value: nosniff
