/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "book": {
    name: "book",
    description: "A book component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/srisomanaath/book.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/styles/book.css",
      type: "registry:style",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/srisomanaath/book.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "modern-progress": {
    name: "modern-progress",
    description: "A modern progress component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/srisomanaath/modern-progress.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/srisomanaath/modern-progress.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pixel-icon": {
    name: "pixel-icon",
    description: "A pixel icon component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/srisomanaath/pixel-icon.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/srisomanaath/pixel-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-text-effect": {
    name: "split-text-effect",
    description: "A split text effect component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/srisomanaath/split-text-effect.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/srisomanaath/split-text-effect.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "view-magnifier": {
    name: "view-magnifier",
    description: "A view magnifier component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/srisomanaath/view-magnifier.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/srisomanaath/view-magnifier.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "game-of-life": {
    name: "game-of-life",
    description: "A game of life component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/srisomanaath/game-of-life.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/srisomanaath/game-of-life.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "magical-mouse": {
    name: "magical-mouse",
    description: "A magical mouse component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/srisomanaath/magical-mouse.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/srisomanaath/magical-mouse.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "book-demo": {
    name: "book-demo",
    description: "A demo of the Book component",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/book"],
    files: [{
      path: "registry/example/book-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/book-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "book-variant-demo": {
    name: "book-variant-demo",
    description: "A demo of the Book component with variants",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/book"],
    files: [{
      path: "registry/example/book-variant-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/book-variant-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "game-of-life-demo": {
    name: "game-of-life-demo",
    description: "A demo of the Game of Life component",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/game-of-life"],
    files: [{
      path: "registry/example/game-of-life-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/game-of-life-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "game-of-life-demo-2": {
    name: "game-of-life-demo-2",
    description: "A demo of the Game of Life component with variants",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/game-of-life"],
    files: [{
      path: "registry/example/game-of-life-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/game-of-life-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "magical-mouse-demo": {
    name: "magical-mouse-demo",
    description: "A demo of the Magical Mouse component",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/magical-mouse"],
    files: [{
      path: "registry/example/magical-mouse-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/magical-mouse-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "modern-progress-demo": {
    name: "modern-progress-demo",
    description: "A demo of the Modern Progress component",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/modern-progress"],
    files: [{
      path: "registry/example/modern-progress-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/modern-progress-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pixel-icon-demo": {
    name: "pixel-icon-demo",
    description: "A demo of the Pixel Icon component",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/pixel-icon"],
    files: [{
      path: "registry/example/pixel-icon-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/pixel-icon-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-text-effect-demo": {
    name: "split-text-effect-demo",
    description: "A demo of the Split Text Effect component",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/split-text-effect"],
    files: [{
      path: "registry/example/split-text-effect-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/split-text-effect-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-text-effect-demo-2": {
    name: "split-text-effect-demo-2",
    description: "A demo of the Split Text Effect component with variants",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/split-text-effect"],
    files: [{
      path: "registry/example/split-text-effect-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/split-text-effect-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "split-text-effect-demo-3": {
    name: "split-text-effect-demo-3",
    description: "A demo of the Split Text Effect component with variants",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/split-text-effect"],
    files: [{
      path: "registry/example/split-text-effect-demo-3.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/split-text-effect-demo-3.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "view-magnifier-demo": {
    name: "view-magnifier-demo",
    description: "A demo of the View Magnifier component",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/view-magnifier"],
    files: [{
      path: "registry/example/view-magnifier-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/view-magnifier-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "view-magnifier-demo-2": {
    name: "view-magnifier-demo-2",
    description: "A demo of the View Magnifier component with variants",
    type: "registry:example",
    registryDependencies: ["@srisomanaath/view-magnifier"],
    files: [{
      path: "registry/example/view-magnifier-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/view-magnifier-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "book-styles": {
    name: "book-styles",
    description: "",
    type: "registry:style",
    registryDependencies: undefined,
    files: [{
      path: "registry/styles/book.css",
      type: "registry:style",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/styles/book.css")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }